### PR TITLE
Added For Each looping.

### PR DESCRIPTION
**Pull request by martinhbramwell**
Hi Dave,

I hope you approve of my little contribution.

As far as I can tell I haven't broken anything.

Regards,
Hasan

### CODE REVIEW

**Comment by martinhbramwell** [comment]
Btw.  I'm using Git client "SmartGit 2.1.4"  It's file version comparator is _way_ better than the diff offered here by GitHub.  Contrary to GitHub's diff, I have NOT changed everything completely.

**Comment by davehunt** [comment]
Thanks for this pull request. I've merged, tested, made a couple of small tweaks, and will soon be pushing the update to AMO.

**Comment by davehunt** [comment]
Thanks for this pull request. I've merged, tested, made a couple of small tweaks, and will soon be pushing the update to AMO.

**Comment by davehunt** [comment]
Thanks for this pull request. I've merged, tested, made a couple of small tweaks, and will soon be pushing the update to AMO.

**Comment by martinhbramwell** [comment]
Dave!, that's really great!  Thank you.  

You might want to have a look at this :  https://github.com/martinhbramwell/SEL-Blocks

After all the work I did on SideFlow, I realized that SEL-Block's capabilities better suited what I am doing, so I ported the JSON ForEach functionality into it as well.

You can see the scripts, for which the JSON looping was necessary, (support for OpenERP training) here : https://github.com/martinhbramwell/SeleniumForOpenERP

**Pull request merged**
